### ISSUE TITLE
Please add an workflow json file to explain how to use this node

### ISSUE THREAD

**Issue by pivtienduc** [maepopi/Diffusers-in-ComfyUI#4]
Hi @maepopi 

Thank you for writing this node. Can you explain how to use it?

I try to download diffusers from Huggingface into my PC and run it by your node.

Where should I put diffusers file do I need to make a subfolder with a same structure like on Huggingface

Can I use your node with save checkpoint to convert several pytorch file into just 1 safetensor file. 

![image](https://github.com/user-attachments/assets/8a5b5200-0e8f-474e-93f2-7b5d8f2d3c27)

Thank in advance

**Comment by maepopi** [comment]
Hello!

I'll try and make a json workflow some time in the next few days, but what I can already tell you is that you simply need to put your model (I suppose that's what you mean by "diffusers") inside the "checkpoints" folder of your ComfyUI installation. Then, inside Comfy UI, you'll be able to find your model with the "Load checkpoint" node.
![image](https://github.com/user-attachments/assets/c4043319-6091-4c24-8646-62ca4bffa876)

For now, you can only load a single checkpoint / safetensor model, I haven't implemented the possibility to retrieve the model remotely via hugging face. It was something I needed to update, though, so I'll definitely add it to my todo list.

As for the conversion of torch files into safetensors, unfortunately no I haven't designed any node that does that internally in Comfy but I can have a look at it, see how I can incorporate it.

While waiting for a .json workflow, I hope this answer will already help you a bit,

Kind regards,

**Comment by pivtienduc** [comment]
> Hello!
> 
> I'll try and make a json workflow some time in the next few days, but what I can already tell you is that you simply need to put your model (I suppose that's what you mean by "diffusers") inside the "checkpoints" folder of your ComfyUI installation. Then, inside Comfy UI, you'll be able to find your model with the "Load checkpoint" node. ![image](https://private-user-images.githubusercontent.com/35258413/393155508-c4043319-6091-4c24-8646-62ca4bffa876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzI2NzYsIm5iZiI6MTczMzQ3MjM3NiwicGF0aCI6Ii8zNTI1ODQxMy8zOTMxNTU1MDgtYzQwNDMzMTktNjA5MS00YzI0LTg2NDYtNjJjYTRiZmZhODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA4MDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZWMwOTkzMzJjZGViMDE2MTczMTFkYmE4YzIzMTg4M2VhNzA3YzMwYjUxMTgzYzVhYWE0YWFlNzcxYzkxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LNqMIUFluX9G7lPEdjOsXIc1HXNIzAx6020pN044Xnc)
> 
> For now, you can only load a single checkpoint / safetensor model, I haven't implemented the possibility to retrieve the model remotely via hugging face. It was something I needed to update, though, so I'll definitely add it to my todo list.
> 
> As for the conversion of torch files into safetensors, unfortunately no I haven't designed any node that does that internally in Comfy but I can have a look at it, see how I can incorporate it.
> 
> While waiting for a .json workflow, I hope this answer will already help you a bit,
> 
> Kind regards,

Thank you for your quick answer. I'm waiting for your update. Cheer

**Comment by maepopi** [comment]
There was a small mistake in what I told you. In my nodes,you don't use Comfy's Load checkpoint node to load your model. I've rebuilt the Diffusers pipeline without going through Comfy so that's a whole separate pipeline.
Here's an image of a very generic pipeline to generate an image with SD 1.5 Text to Image.

![image](https://github.com/user-attachments/assets/d74cde97-f646-4a4a-94cd-6be5e572c4f8)

As you can see, the model is loaded in the node Txt2ImgStableDiffusionPipeline, which you can find in "Diffusers-in-ComfyUI > Pipelines"

I can see now the need for examples jsons! I'll do a couple this week end.

Kind regards

**Comment by maepopi** [comment]
Hi again, 

I've used my lunch break to create an "examples" folder : inside it you'll find json workflow examples, as well as screenshots. I've also detailed the Readme a bit more to add in the screenshots.

Pull the latest version and check it out! Hope this helps, otherwise I'll do more guides.

Kind regards

**Comment by wardensc2** [comment]
> Hi again,
> 
> I've used my lunch break to create an "examples" folder : inside it you'll find json workflow examples, as well as screenshots. I've also detailed the Readme a bit more to add in the screenshots.
> 
> Pull the latest version and check it out! Hope this helps, otherwise I'll do more guides.
> 
> Kind regards

Hi I try to install your updated node but unfortunately I use updated version of ComfyUI which use cuda 1.2.4 and pytorch 2.5.1 so I dont want to use xformer and old version of CUDA again so your node can't work. Anyway thank for your passionated support

**Comment by maepopi** [comment]
Ah ! Yes Xformers is pretty much a pain in the ass on Windows... 😅 Ok I'll see what I can do this week end to make the xformers option well...optional!
Maybe I should make a docker for Windows users as well, that might be useful.

**Comment by maepopi** [comment]
Hi there again,
So I've fixed a few things:
- Removed Xformers memory attention for CPU pipeline
- Rewrote and simplified the installation steps
- Updated the requirements.txt which caused errors

I'm closing this thread, but don't hesitate opening another one to clearly distinguish the issues!

Thanks,

Best
